project:
  type: website

website:
  title: "nondeterministic woodlands"
  description: "Some guy's journey to a PhD in geospatial data analysis"
  site-url: https://pedantic-yalow-e71f1a.netlify.app
  repo-url: https://github.com/iod-ine/nondeterministic-woodlands
  repo-actions: [source, issue]
  search: true
  favicon: images/favicon.ico
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/iod-ine/nondeterministic-woodlands
  body-header: ---
  margin-header: |
    ![](https://raw.githubusercontent.com/iod-ine/nondeterministic-woodlands/main/images/logo.svg)
format:
  html:
    theme: sandstone
    css: styles.css
